### ISSUE TITLE
RangeError (byteOffset): Invalid value: Not in range 0..248, inclusive: 252

### ISSUE THREAD

**Issue by simc** [dart-portals/binary#1]
The following code throws an exception:

```dart
import 'package:binary/binary.dart';

void main() {
  var writer = BytesWriter();
  for (var i = 0; i < 1000; i++) {
    writer.write(123123);
  }
}
```

Exception:
```
Unhandled exception:
RangeError (byteOffset): Invalid value: Not in range 0..248, inclusive: 252
#0      _ByteDataView.setFloat64  (dart:typed_data-patch/typed_data_patch.dart:4513:7)
#1      BytesWriter.writeFloat64 package:binary/src/binary.dart:75
#2      PrimitiveTypesWriter.writeDouble package:binary/…/adapters/core.dart:7
#3      PrimitiveTypesWriter.writeInt package:binary/…/adapters/core.dart:8
#4      AdapterForInt.write package:binary/…/adapters/core.dart:52
#5      BinaryWriter.write package:binary/src/source.dart:30
#6      main main.dart:6
#7      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:307:19)
#8      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by simc** [comment]
@marcelgarus Did you have time to give it a quick look? Am I doing something wrong? Would be cool to compare our solutions in order to decide how to move forward with Hive 2.0 :+1:

**Comment by MarcelGarus** [comment]
Sorry, I didn't look deeper into it yet – currently, I'm a bit busy with exams.
Although I'll probably change the encoding of integers to be more efficient anyway, so I'm sure that error will be resolved in a future version.

**Comment by MarcelGarus** [comment]
The newest version shouldn't have that error anymore 😊
