### ISSUE TITLE
Invalid value: Not in range 0..252, inclusive: 254

### ISSUE THREAD

**Issue by simc** [dart-portals/binary#2]
I'm still getting an error with the following code:

```dart
import 'package:binary/binary.dart';

void main() {
  var writer = BytesWriter();
  for (var i = 0; i < 1000; i++) {
    writer.write(123123);
  }
}
```

Exception:
```
Unhandled exception:
RangeError (byteOffset): Invalid value: Not in range 0..252, inclusive: 254
#0      _ByteDataView.setUint32  (dart:typed_data-patch/typed_data_patch.dart:4576:7)
#1      BinaryWriter.writeUint32  package:binary/src/binary_writer.dart:63
#2      AdapterForUint32.write  package:binary/…/adapters/int.dart:67
#3      BinaryWriter.write  package:binary/src/binary_writer.dart:46
#4      main  main.dart:6
#5      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
#6      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
```

Edit: Sorry, probably should have reopened the old issue...

**Comment by MarcelGarus** [comment]
Oh, there was an issue in how the `BinaryWriter` reserved memory. I fixed it now.
